doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Docplanner:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Docplanner/Domain/Model'
                prefix: 'App\Docplanner\Domain\Model'
                alias: Docplanner
            Shared:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Shared/Model'
                prefix: 'App\Shared\Model'
                alias: Shared
