# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\Shared\Symfony\Listener\InputValidationExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  App\Shared\Symfony\ParamConverter\InputFactoryServiceLocator:
    arguments:
      - !tagged_locator {tag: action.input_factory, index_by: key, default_index_method: 'supports'}

  App\Shared\Symfony\InputFactory\InputValidator:
    class: App\Shared\Symfony\InputFactory\SymfonyValidator

  App\Shared\Symfony\ParamConverter\ActionInputParamConverter:
    tags:
      - { name: request.param_converter, converter: converter.action_input, priority: false }

  App\Shared\Symfony\Response\ResponseFactory:
    class: App\Shared\Symfony\Response\JsonResponseFactory

  App\Shared\Symfony\Response\ResponseEventListener:
    arguments:
      - '@App\Shared\Symfony\Response\ResponseFactory'
      - '@annotations.reader'
    tags:
      - { name: kernel.event_listener, event: kernel.view }

  App\Example\Application\TestActionInputFactory:
    tags:
      - { name: action.input_factory }

  get_set_method_normalizer:
    class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
    tags: [ serializer.normalizer ]
